<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="FB_ClearOutputBuffer" Id="{413b5d5d-fe97-428e-94b2-30caf36f72c6}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ClearOutputBuffer
VAR_INPUT
	OutputBufferAddress				: PVOID;
	SizeOfOutputBuffer				: UDINT;
END_VAR
VAR_OUTPUT
END_VAR
VAR
	NullItem						: BYTE 		:= 0;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[
MEMSET(OutputBufferAddress,
		NullItem,
		SizeOfOutputBuffer);]]></ST>
    </Implementation>
    <LineIds Name="FB_ClearOutputBuffer">
      <LineId Id="22" Count="0" />
      <LineId Id="11" Count="1" />
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>